// src/db.ts
import Dexie from "dexie";

/**
 * Defines the structure of a Note object that will be stored in the database.
 * The 'id' is optional because it will be auto-generated by IndexedDB.
 */
export interface Note {
  id?: number;
  title: string;
  content: string;
  timestamp: Date;
}

/**
 * A class that defines the database schema using Dexie.js.
 * It creates a database named 'EarthquakeNotesDB' and defines a 'notes' table.
 */
export class NotesDB extends Dexie {
  // 'notes' is a property that represents the table. Dexie populates this.
  notes!: Dexie.Table<Note>;

  constructor() {
    super("EarthquakeNotesDB");
    // Define the database schema. This is version 1.
    this.version(1).stores({
      // The 'notes' table has an auto-incrementing primary key 'id' and is indexed by 'timestamp'.
      notes: "++id, title, content, timestamp",
    });
  }
}

// Export a singleton instance of the database to be used throughout the application.
export const db = new NotesDB();
